""" please go through the docs before running this scripts """

from twilio.rest import Client

print("\n" + " *****        WELCOME TO AUTOMATED PYTHON CALLING SCRIPT       ***** ")
print(" *****  PLEASE CREATE A TWILIO ACCOUNT BEFORE USING THE SCRIPT ***** ")
print(" *****      TO CREATE TWILIO ACCOUNT GO TO WWW.TWILIO.COM      ***** ")
print(" *****            TYPE 'YES/yes'  IF YOU WANT TO PROCEED       ***** "+'\n')
i = input()
print("\n")


if (i == "YES" or i == "yes"):
    account_sid = input(" ENTER YOUR TWILIO ACCOUNT-SID ")
    auth_token = input(" ENTER YOUR TWILIO AUTH-TOKEN  ")

    client = Client(account_sid, auth_token)

    print("**** press 1 for single phone number    *****")
    print("**** press 2 for multiple phone numbers *****")
    i = int(input())

    if (i == 1):
        print(" ***** PLEASE ENTER RECIEVER's NUMBER **note mention your country code followed by '+' *****")
        number = int(input())
        print(" ***** PLEASE ENTER YOUR AUTOGENERATED NUMBER **note mention your country code followed by '+' *****")
        my_number = int(input())
        """ client.calls.create will be responsible for the call process 
            also here url is the reponse urls , i.e whatever you want to
            give as a response to the reciever you can give by simply creating your
            own at twilio.com, since it is a trail we have used trail response     
            
            'to' attribute specifies whom you want to dial
            'from' attribute specifies from which number the receiver will receive the call
             **note that number will be auto genrated in the trail process

        """
        call = client.calls.create(
            url='http://demo.twilio.com/docs/voice.xml',
            to=number,
            from_=my_number
        )
        print(" call success ")

    if (i == 2):
        print(" ***** PLEASE ENTER RECIEVER's NUMBER SEPARTED BY SPACE **note mention your country code followed by '+' *****")
        number = list(int(i) for i in input().strip().split(' '))
        print(" ***** PLEASE ENTER YOUR AUTOGENERATED NUMBER **note mention your country code followed by '+' *****")
        my_number = int(input())
        """ client.calls.create will be responsible for the call process 
            also here url is the reponse urls , i.e whatever you want to
            give as a response to the reciever you can give by simply creating your
            own at twilio.com, since it is a trail we have used trail response     
            
            'to' attribute specifies whom you want to dial
            'from' attribute specifies from which number the receiver will receive the call
             **note that number will be auto genrated in the trail process

        """
        for i in number:
            call = client.calls.create(
                url='http://demo.twilio.com/docs/voice.xml',
                to=i,
                from_=my_number
            )
            print(" call success to the number " + str(i))
